version: '2.3'
services:
  expense_app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py runserver 0.0.0.0:8100 && celery worker -A payee_name -l INFO --beat --concurrency=2 -n 'main_app'"
    volumes:
      - .:/app
    ports:
      - "8100:8100"
    environment:
      BUDGET_PASSWORD: ${BUDGET_PASSWORD}
    container_name: expense_app
    networks:
      - expense_network
    restart:
      always  
    
  
  rabbitmq:
    image: 'bitnami/rabbitmq:3.7'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - 'expense_elk_data:/bitnami'
    networks:
      - expense_network
    restart:
      always

  elasticsearch:
    build:
      context: ../expense_elk/elasticsearch/
      args:
        ELK_VERSION: 7.0.1
    volumes:
      - ../expense_elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /etc/timezone:/etc/timezone
      - ../expense_elk/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx2560m -Xms2560m"
      ELASTIC_PASSWORD: Dscw1800
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"
    networks:
      - expense_network
    restart:
      always

  kibana:
    build:
      context: ../expense_elk/kibana/
      args:
        ELK_VERSION: 7.0.1
    volumes:
      - ../expense_elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - /etc/timezone:/etc/timezone
    ports:
      - "5601:5601"
    networks:
      - expense_network
    depends_on:
      - elasticsearch
    restart:
      always

  
volumes:
  expense_elk_data:
    external: true
  
networks:
  expense_network:
    driver: overlay