version: '3.8'

services:
  expense_app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8100"
    volumes:
      - .:/app
      - /root/db/:/root/db/
    ports:
      - "8100:8100"
    env_file:
      - .env
    environment:
      BUDGET_PASSWORD: "${BUDGET_PASSWORD}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      ELASTIC_PASSWORD: "${ELASTIC_PASSWORD}"
    depends_on:
      - expense_worker
      - elasticsearch
      - expense_db
    container_name: expense_app
    networks:
      expense_network:
        ipv4_address: "10.10.0.2"
    restart:
      always

  expense_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "celery -A payee_name worker --loglevel INFO --concurrency=1 -n 'main_app' & celery -A payee_name beat --loglevel INFO"
    volumes:
      - .:/app
    ports:
      - "8200:8200"
    env_file:
      - .env
    environment:
      BUDGET_PASSWORD: "${BUDGET_PASSWORD}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      ELASTIC_PASSWORD: "${ELASTIC_PASSWORD}"
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
      - elasticsearch
      - expense_db
    container_name: expense_worker
    networks:
      expense_network:
        ipv4_address: "10.10.0.3"
    restart:
      always

  expense_db:
    image: "postgres:14"
    container_name: expense_db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_HOST: "expense_host"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "expense"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "Expenses"
      PG_DATA: "/var/lib/postgresql/data"
      TZ: "UTC"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    networks:
      expense_network:
        ipv4_address: "10.10.0.4"
  
  rabbitmq:
    image: "rabbitmq"
    hostname: "rabbitmq"
    env_file:
      - .env
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - '5672:5672'
      - '15672:15672'
    labels:
      NAME: "rabbitmq"
    container_name: rabbitmq
    volumes:
      - 'expense_elk_data:/bitnami'
    networks:
      expense_network:
        ipv4_address: "10.10.0.5"
    restart:
      always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_PASSWORD="${ELASTIC_PASSWORD}"
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ../expense_elk/elasticsearch/config:/usr/share/elasticsearch/config
      - /etc/timezone:/etc/timezone
      - ../expense_elk/elasticsearch/data:/usr/share/elasticsearch/data
    env_file:
      - .env
    container_name: elasticsearch
    networks:
      expense_network:
        ipv4_address: "10.10.0.6"
    restart:
      always
    user: "1000:1000"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.0
    environment:
      ELASTICSEARCH_URL: "http://10.10.0.6:9200"
      ELASTICSEARCH_HOSTS: "http://10.10.0.6:9200"
    volumes:
      - ../expense_elk/kibana/config:/usr/share/kibana/config
      - /etc/timezone:/etc/timezone
    ports:
      - "5601:5601"
    networks:
      expense_network:
        ipv4_address: "10.10.0.7"
    container_name: kibana
    depends_on:
      - elasticsearch
    restart:
      always


volumes:
  expense_elk_data:
    external: true
  
networks:
  expense_network:
    name: expense_network
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1