# Generated by Django 2.1.2 on 2018-12-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('sub_category', models.CharField(max_length=500)),
                ('payment_method', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('ref_checkno', models.CharField(max_length=500)),
                ('payee_payer', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('receipt_picture', models.CharField(max_length=500)),
                ('account', models.CharField(max_length=500)),
                ('tag', models.CharField(max_length=500)),
                ('tax', models.CharField(max_length=500)),
                ('mileage', models.CharField(max_length=500)),
            ],
        ),
    ]
