# Generated by Django 2.1.2 on 2018-12-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0002_expenses'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expenses',
            table='Expenses',
        ),
    ]
