# Generated by Django 2.2.3 on 2019-08-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0005_auto_20190826_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.IntegerField(default=0.0),
        ),
    ]
