# Generated by Django 2.2.3 on 2026-06-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0007_auto_20190903_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantCategoryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_key', models.CharField(max_length=500, unique=True)),
                ('merchant_display', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('sub_category', models.CharField(default='Unknown', max_length=500)),
                ('source', models.CharField(default='manual', max_length=100)),
                ('confidence', models.FloatField(default=1.0)),
                ('times_used', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'MerchantCategoryMapping',
            },
        ),
    ]
