# Generated by Django 2.2.13 on 2026-06-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0008_merchantcategorymapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='tag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
